### ISSUE TITLE
SendInputFocus broken + possibly others

### ISSUE THREAD

**Issue by IsaacElenbaas** [tych0/xcffib#104]
Here is what I am trying to run [(full file)](https://pastebin.com/4mAt5aj2):
`xcb.xproto.xprotoExtension.SetInputFocus(conn, xcb.xproto.InputFocus.PointerRoot, window, xcb.CurrentTime)`
and I get this error:
```
  File "./launcher.py", line 50, in startup
    xcb.xproto.xprotoExtension.SetInputFocus(conn, xcb.xproto.InputFocus.PointerRoot, window, xcb.CurrentTime)
  File "/usr/lib/python3.8/site-packages/xcffib/xproto.py", line 2809, in SetInputFocus
    return self.send_request(42, buf, is_checked=is_checked)
TypeError: wrapper() got an unexpected keyword argument 'is_checked'
```

I tried removing the `is_checked` param from SendInputFocus, but that broke the creation of [xcb-req](https://github.com/tych0/xcffib/blob/master/module/__init__.py#L369) somehow and [this](https://github.com/tych0/xcffib/blob/master/module/__init__.py#L391) threw an error (called by `f(*args)` in `wrapper`).
```
  File "./launcher.py", line 50, in startup
    xcb.xproto.xprotoExtension.SetInputFocus(conn, xcb.xproto.InputFocus.PointerRoot, window, xcb.CurrentTime)
  File "/usr/lib/python3.8/site-packages/xcffib/xproto.py", line 2809, in SetInputFocus
    return self.send_request(42, buf)
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
TypeError: send_request() missing 1 required positional argument: 'xcb_req'
```
@tych0 suggested adding `**kwargs` [here](https://github.com/tych0/xcffib/blob/master/module/__init__.py#L567) and [here](https://github.com/tych0/xcffib/blob/master/module/__init__.py#L571), as the original issue was the wrapper complaining. It is then thrown by the same line as when I removed the param, but now due to too many arguments where there were too few if `is_checked` wasn't passed.
```
  File "./launcher.py", line 50, in startup
    xcb.xproto.xprotoExtension.SetInputFocus(conn, xcb.xproto.InputFocus.PointerRoot, window, xcb.CurrentTime)
  File "/usr/lib/python3.8/site-packages/xcffib/xproto.py", line 2809, in SetInputFocus
    return self.send_request(42, buf, is_checked=is_checked)
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args, **kwargs)
TypeError: send_request() got an unexpected keyword argument 'is_checked'
```

So the wrapper definitely needs `**kwargs`, but I'm not certain why `send_request` does not work with or without `is_checked`.

**Comment by IsaacElenbaas** [comment]
Maybe `seq = self.conn.send_request` would throw as just `send_request`. It could be one or the other getting angry depending on whether `is_checked` is passed, rather than some magic where one somehow gains/loses two variables when we toggle one.

**Comment by tych0** [comment]
Oh, I think I see the issue. See how we call SetInputFocus in qtile: https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/xcbq.py#L461

I think you want to call it via `conn.core.SetInputFocus()` instead of `xcffib.xproto.SetInputFocus`

**Comment by IsaacElenbaas** [comment]
No errors and I don't get keypresses in the terminal I'm running it from until I manually change windows at least once, appears to work. Thanks! Should I not use things under `xcffib.xproto.xprotoExtension` or is this a special case? I'd just searched for SetInputFocus for a while as it wasn't in `xproto` as expected and came across `xprotoExtension`.

**Comment by tych0** [comment]
On Wed, Jul 08, 2020 at 02:31:48PM -0700, Isaac Elenbaas wrote:
> No errors and I don't get keypresses in the terminal I'm running it from until I manually change windows at least once, appears to work. Thanks! Should I not use things under `xcffib.xproto.xprotoExtension` or is this a special case? I'd just searched for SetInputFocus for a while as it wasn't in `xproto` as expected and came across `xprotoExtension`.

Yeah, there's a whole undocumented (terrible) API for accessing
core/extensions, mostly the tests have examples of how to use it, or
qtile does. xpyb gifted us this, and there's not much we can do about
it unfortunately :(

**Comment by tych0** [comment]
On Wed, Jul 08, 2020 at 02:31:48PM -0700, Isaac Elenbaas wrote:
> No errors and I don't get keypresses in the terminal I'm running it from until I manually change windows at least once, appears to work. Thanks! Should I not use things under `xcffib.xproto.xprotoExtension` or is this a special case? I'd just searched for SetInputFocus for a while as it wasn't in `xproto` as expected and came across `xprotoExtension`.

Although perhaps we should do something if people are just accessing
the extension directly? Like throw an exception or something? I'd
definitely take a patch that does that.
