### ISSUE TITLE
Missing git tag for 0.10.0 release

### ISSUE THREAD

**Issue by felixonmars** [tych0/xcffib#105]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by tych0** [comment]
Oof, yes, thanks. I tagged it locally, just didn't push it. I've pushed it now, thanks!

**Comment by felixonmars** [comment]
Sorry to bother you, but it looks like 0.10.1 is missing again ._.

**Comment by tych0** [comment]
Derp :)
