### ISSUE TITLE
Check if `Xvfb` dies before trying to connect

### ISSUE THREAD

**Issue by ep12** [tych0/xcffib#115]
@tych0 As initially mentioned [here](https://github.com/qtile/qtile/pull/2331#discussion_r604924629), I currently cannot run the qtile test suite. Debugging the test suite is not that easy, but I managed to find out that tests with `Xvfb` don't start (the setup phase hangs and only times out with `pytest-timeout` and `timeout_method = thread`).
Somehow `Xvfb` doesn't start on my system (don't know why yet), but it might be a good idea to check if the process died before everything hangs when trying to connect to it here:
https://github.com/tych0/xcffib/blob/a0530fa05c4289d8c747aa23d401057dc01d1528/module/testing.py#L127
Something like this would probably be a good start:
```py
def _connect_to_xvfb(self):
    if self._xvfb.poll() is not None:  # None: still running
        raise ConnectionError('Could not connect to Xvfb')
    try:
        ...
```
That way the source of the issue would be easier to spot.

**Comment by tych0** [comment]
The connection shouldn't hang; if it does, xvfb is running and something else is going on. It should fail fast here.

**Comment by ep12** [comment]
Okay, digging deeper and more strange things happen. It seems like `lib.xcb_connect` fails in `__init__.py:525`. But why?

**Comment by tych0** [comment]
How does it fail? It hangs? It throws an exception?

**Comment by tych0** [comment]
Might be worth using the xtrace stuff.

**Comment by ep12** [comment]
Doing `lib.xcb_connect(b':30', i)` when I manually start `Xvfb :30 -screen :0 800x600x16` the connection attempt works immediately. In the tox venv it fails...

**Comment by tych0** [comment]
> Is Xvfb as used above supposed to create a window on :0?

No. It's supposed to capture everything so that you can run the tests in headless mode.

>  I tried prepending xtrace to the Xvfb

Sorry, I meant just setting xtrace = True in XvfbTest. it should do all that stuff for you.

See about stracing things as well, to see where they are stuck, etc.

**Comment by ep12** [comment]
Ah, stupid me. Seems like `glibc` provides an `xtrace` command. I thought I had the right `xtrace` as in `X trace` installed :facepalm:.

**Comment by ep12** [comment]
This is the `x11trace` output when it hangs, basically a single line:
```
-> conn = Connection(os.environ['DISPLAY'])
(Pdb) n
Got connection from unknown(local)
000:<: am lsb-first want 11:0 authorising with '' of length 0
```
Before that `x11trace` only prints `No display name to create specified, trying :9`

**Comment by tych0** [comment]
Did you set DISPLAY=:9?

**Comment by tych0** [comment]
> os.environ['DISPLAY'] = ':9'

So, this isn't the right place to set this. But in any case, XvfbTest should handle it for you, so it shouldn't matter.

Might be worth not swallowing the output of xvfb to see if it mentions anything. An strace will also be informative, I'm guessing.

**Comment by ep12** [comment]
Ok. I applied
```diff
--- /usr/lib/python3.9/site-packages/xcffib/testing.py	2020-12-24 15:00:54.000000000 +0100
+++ .tox/py39/lib/python3.9/site-packages/xcffib/testing.py	2021-04-06 19:42:36.080902286 +0200
@@ -29,7 +29,7 @@ def lock_path(display):
 
 
 def find_display():
-    display = 10
+    display = 9
     while True:
         try:
             f = open(lock_path(display), "w+")
@@ -52,7 +52,7 @@ class XvfbTest(object):
 
     # Set this to true if you'd like to get xtrace output to stdout of each
     # test.
-    xtrace = False
+    xtrace = True
 
     def __init__(self, width=800, height=600, depth=16):
         self.width = width
@@ -61,7 +61,8 @@ class XvfbTest(object):
 
     def spawn(self, cmd):
         """ Spawn a command but swallow its output. """
-        return subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
+        print('Spawning %s' % cmd)
+        return subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
 
     def setUp(self):
         self._old_display = os.environ.get('DISPLAY')
@@ -118,12 +119,19 @@ class XvfbTest(object):
         whatever. At this point, os.environ['DISPLAY'] is set to something Xvfb
         can use. """
         screen = '%sx%sx%s' % (self.width, self.height, self.depth)
-        return ['Xvfb', os.environ['DISPLAY'], '-screen', '0', screen]
+        return ['Xvfb', '-core', os.environ['DISPLAY'], '-screen', '0', screen]
 
     def _connect_to_xvfb(self):
         # sometimes it takes a while for Xvfb to start
         for _ in range(100):
             try:
+                so, se = self._xvfb.communicate(timeout=1)
+                print('<stdout>:\n' + so.decode())
+                print('<stderr>:\n' + se.decode())
+            except Exception:
+                pass
+            print('Trying to connect (%d)' % _)
+            try:
                 conn = Connection(os.environ['DISPLAY'])
                 conn.invalid()
                 return conn
```
and got the same sparse output:
```
test/test_bar.py::test_draw[GBConfig] 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Captured stdout ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Spawning ['Xvfb', '-core', ':9', '-screen', '0', '800x600x16']
Trying to connect (0)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Captured stderr ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
No display name to create specified, trying :9
```
After that the same traceback is shown.

**Comment by ep12** [comment]
I did two more runs:
1. start `tox -e py39` to get the `Xvfb` running on `:9` and then run a short script outside the venv: [xcffib_strace.log](https://github.com/tych0/xcffib/files/6266743/xcffib_strace.log)
1. Start `Xvfb :9 -screen 0 800x600x16` manually outside the qtile test suite venv and then run the same script again: [xcffib_strace_non_tox.log](https://github.com/tych0/xcffib/files/6266746/xcffib_strace_non_tox.log)

The `Xvfb` started inside the venv causes trouble, the one started outside works perfectly and the script exits with code 0:
```py
from xcffib import xproto, ffi, lib
i = ffi.new('int *')
print('connecting...')
c = lib.xcb_connect(b':9', i)
print('disconnecting')
lib.xcb_disconnect(c)
```

**Comment by tych0** [comment]
Check its environment, e.g. does it have a reasonable DISPLAY inside the venv? I suspect venv clears a lot of that stuff out.

**Comment by ep12** [comment]
`tox` has `passenv = DISPLAY TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH`, so `DISPLAY` should be set to `:0`. The strange thing is that those hangs started to occur around a week ago. Until then everything worked fine, after that nothing works, no matter which commit I check out. But then the only update that seems related is `python-gobject`. TBH I didn't check all the updated packages for links to qtile.

**Comment by tych0** [comment]
`git bisect` will be useful here.

**Comment by ep12** [comment]
Bisect what? The problem is that I can checkout commits now and the tests don't work even if they ran successfully a week ago or so. I also did a fresh git clone of the qtile repo and the same issue occurs. So it doesn't have to do with temporary files in the .tox folder or elsewhere inside the local clone.

`DISPLAY=:0` inside the venv started with tox. Just verified it with pdb before running the first test.

**Comment by ep12** [comment]
Any clue what I should reinstall that could've been broken by the installation of updates? Already reinstalled xcffib with no luck at all...

**Comment by tych0** [comment]
Oh, sorry, I misread you had said it still worked with commits a week ago.

**Comment by ep12** [comment]
Yet another strange thing: If I prevent the `testing.py` from trying to connect to Xvfb, the external connection is established successfully. So: `testing.py` spawns Xvfb, then I told it to wait for 20 seconds. During that time I can use the script outside the venv to connect to that Xvfb instance without any problems. And then `testing.py` goes on and tries to connect to the instance it spawned. And it still hangs.

**Comment by ep12** [comment]
And the test suite also hangs in a manjaro vm with a fresh Xvfb install and a fresh clone.
