### ISSUE TITLE
Invalid Unpacker.synthetic

### ISSUE THREAD

**Issue by amerlyq** [tych0/xcffib#118]
Broken code. Must pass "known_max" and return self:
```python
# /usr/lib/python3.9/site-packages/xcffib/__init__.py:126
# class Unpacker(object):
      @classmethod
      def synthetic(cls, data, format):
          self = cls.__new__(cls)
          self.buf = data
          self.offset = 0
          self.size = len(data)
          self.size
```

**Comment by tych0** [comment]
I agree; can you send a patch for those? (also dropping the last line there that's a no-op?)

**Comment by amerlyq** [comment]
Sorry, no monkey patch for this one, it seems I did not used this one in my code.
Simply spotted the issue during implementation.
