### ISSUE TITLE
xcffibgen fails with "Non-exhaustive patterns in function structElemToPyPack"

### ISSUE THREAD

**Issue by felixonmars** [tych0/xcffib#139]
Hi, I am getting this error when packaging xcffib for Arch:

```
xcffibgen --input //usr/share/xcb --output ./xcffib
bigreq
composite
damage
dbe
dpms
dri2
dri3
ge
glx
present
randr
record
render
res
screensaver
shape
shm
sync
xc_misc
xevie
xf86dri
xf86vidmode
xfixes
xinerama
xinput
xcffibgen: generator/Data/XCB/Python/Parse.hs:(354,1)-(428,56): Non-exhaustive patterns in function structElemToPyPack

make: *** [Makefile:16: xcffib] Error 1
```

Looks like Debian ran into the same problem: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017252

**Comment by felixonmars** [comment]
Looks like https://github.com/tych0/xcffib/pull/120 is relevant. Probably a release would help here :)

**Comment by tych0** [comment]
Indeed, I'll tag and push one tonight. Thanks for the ping. I need some way to remember when someone tags a new xcb-proto to go back and look for these kinds of changes and tag a release if there were any.

**Comment by tych0** [comment]
Ok, I released and uploaded to hackage, but my pypi upload failed. Looking into that now...

**Comment by tych0** [comment]
And https://pypi.org/project/xcffib/0.12.0/ is live. Thanks for the ping, I'll close this for now.
