### ISSUE TITLE
Syntax error (assignment without a variable) in `xinput.py` in 1.1.0 sdist

### ISSUE THREAD

**Issue by mgorny** [tych0/xcffib#144]
Using the `xcffib-1.1.0.tar.gz` sdist from pypi:

```pytb
$ python -c 'import xcffib.xinput'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/xcffib-1.1.0/xcffib/xinput.py", line 1875
    = self.data.pop(0)
IndentationError: unexpected indent
```

This is in `DeviceClass.pack()`:

```python
        if type & DeviceClassType.Valuator:
            self.number = self.data.pop(0)
            self.label = self.data.pop(0)
            self.min = self.data.pop(0)
            self.max = self.data.pop(0)
            self.value = self.data.pop(0)
            self.resolution = self.data.pop(0)
            self.mode = self.data.pop(0)
             = self.data.pop(0)
            buf.write(struct.pack("=HI", self.number, self.label))
            buf.write(self.min.pack() if hasattr(self.min, "pack") else FP3232.synthetic(*self.min).pack())
            buf.write(self.max.pack() if hasattr(self.max, "pack") else FP3232.synthetic(*self.max).pack())
            buf.write(self.value.pack() if hasattr(self.value, "pack") else FP3232.synthetic(*self.value).pack())
            buf.write(struct.pack("=I", self.resolution))
            buf.write(struct.pack("=B", self.mode))
            buf.write(struct.pack("=3x", ))
```

**Comment by tych0** [comment]
Oof, that's a bad bug, thanks for reporting. I'll see about adding a test to import everything so at least it is syntatically valid as well. I tried flake8 on the generated code, but it seems much too fiddly.

**Comment by tych0** [comment]
1.1.1 should have the fix.

**Comment by tych0** [comment]
Ugh... this generates other bad things: `buf.write(struct.pack("=3x", _))`

**Comment by tych0** [comment]
https://github.com/tych0/xcffib/pull/146 seems like a better fix; i'll release v1.1.2 with that.

**Comment by mgorny** [comment]
Thanks for looking at it. Haskell's not my thingy, so I'll wait for 1.1.2 and then test on my end. I've noticed because byte-compiling complains about invalid syntax (i.e. `python -m compileall`). You may want to use that as a check that would work immediately without other reports than syntax errors. Or, well, just importing stuff manually ;-).

**Comment by tych0** [comment]
Great suggestion, I added that so we will actually fail in the future.

**Comment by tych0** [comment]
Ok, 1.1.2 should be up.

**Comment by mgorny** [comment]
Thanks, 1.1.2 looks good.
