### ISSUE TITLE
Errors building qtile with 1.4.0: `ModuleNotFoundError: No module named 'xcffib.ffi_build'`

### ISSUE THREAD

**Issue by elParaguayo** [tych0/xcffib#155]
I've seen a couple of users posting issues recently. Main error message is:
```
  File "libqtile/backend/x11/xcursors_ffi_build.py", line 25, in <module>
    from xcffib.ffi_build import ffi as xcffib_ffi
ModuleNotFoundError: No module named 'xcffib.ffi_build'
```

Example error log: https://dpaste.org/ZG7Q9

I had the same issue building in a clean environment and had to drop down to 1.3.0 to get it to build successfully (with that --no-build-isolation flag).

Any reason why 1.4.0 would have broken this?

**Comment by tych0** [comment]
Yep, sorry about that: https://github.com/qtile/qtile/pull/4289

**Comment by tych0** [comment]
I'm gonna close this for now since it's fixed.
