### ISSUE TITLE
xtest.FakeInput() doesn't seem to work

### ISSUE THREAD

**Issue by liftoff** [tych0/xcffib#28]
The following code doesn't do anything and if I execute it enough times it will eventually cause a segmentation fault:

    import xcffib.xtest
    conn = xcffib.connect(display=":1")
    xtest = conn(xcffib.xtest.key)
    XTEST_EVENTS = {
        'KeyPress': 2,
        'KeyRelease': 3,
        'ButtonPress': 4,
        'ButtonRelease': 5,
        'MotionNotify': 6
    }
    # 40 is the 'd' key
    xtest.FakeInput(XTEST_EVENTS['KeyPress'], 40, xcffib.CurrentTime, 4194338, 0, 0, 0, is_checked=True)
    xtest.FakeInput(XTEST_EVENTS['KeyRelease'], 40, xcffib.CurrentTime, 4194338, 0, 0, 0, is_checked=True)
    # 4194338 is an xterm window

It seems similar to the problem I reported in issue #27...  It's like the connection is never being flushed.  Also, if I get in this state and send a whole bunch of keystrokes it will eventually cause a segfault.  `is_checked=True` or `is_checked=False` makes no difference.

If I explicitly call conn.flush() after each call to `xtest.FakeInput()` it won't segfault but it's still not sending KeyPress/KeyEvents like it should.

Using xpyb's `xtest.FakeInputChecked()` works properly.

**Comment by Roger** [comment]
this does not fail, but doesn't trigger events on the window https://github.com/tych0/xcffib/blob/11396a77ef299eb8fb1ac4ab17ffa767b6161749/tests/test_fakeinput.py

**Comment by tych0** [comment]
Phew, finally got around to debugging this. Sorry for the delay, but there's a fix.
