### ISSUE TITLE
Trying to connect without importing xproto will error

### ISSUE THREAD

**Issue by DRMacIver** [tych0/xcffib#43]
The following code raises an exception:

```python
import xcffib
xcffib.connect()
```
This errors as follows:

```
  File "/home/david/.pyenv/versions/2.7.9/lib/python2.7/site-packages/xcffib/__init__.py", line 484, in _init_x
    self.core = core(self)
TypeError: 'NoneType' object is not callable
```
If I change it to

```python
import xcffib
import xcffib.xproto
xcffib.connect()
```

It works fine.

This seems to be because you call the crucial setup function _add_core in xproto, but you don't ever force that to be loaded unless a library user explicitly imports it.

**Comment by tych0** [comment]
Hi,

Thanks for the report. This is actually a hangover form xpyb, although they give you a better error message:

http://cgit.freedesktop.org/xcb/xpyb/tree/src/conn.c#n82

I'll push a fix with a nicer error shortly.

**Comment by tych0** [comment]
Although viz https://github.com/tych0/xcffib/blob/master/module/__init__.py#L193 it would be nice if we could get rid of it without breaking any API compatibility for new users.

**Comment by DRMacIver** [comment]
Ah, I've never actually used xpyb (I try not to use libraries that aren't py3 compatible, so found xcffib when looking around for a modern X library). I just discovered this by ignorantly playing around with the API for the first time.

Thanks for the fix!

**Comment by tych0** [comment]
On Wed, Apr 15, 2015 at 08:50:06AM -0700, David R. MacIver wrote:
> Ah, I've never actually used xpyb (I try not to use libraries that aren't py3 compatible, so found xcffib when looking around for a modern X library). I just discovered this by ignorantly playing around with the API for the first time.

Sure. You'll find a lot of the API isn't all that great :). I'm happy
to merge improvements or enhancements when it doesn't berak xpyb
compatibility, though.
