### ISSUE TITLE
Make sure padding is correct (number of iovecs in `xcb_parts` to pack is different)

### ISSUE THREAD

**Issue by flacjacket** [tych0/xcffib#51]
This is mostly for my own reference, I can try to address this, but I may also be off base on this one. However, this may be why we can't send XIChangeProperty requests correctly (see #49).

Currently, we unconditionally pack 4 iovecs into `xcb_parts` [1], however, I _think_ we might need more if we are packing a list, both with an explicit length parameter and with an implicit length parameter,  (c.f. `xcb_image_text_8` and `xcb_poly_line`, respectively in [2] and [3]). Specifically, we need an additional 2 iovecs for each list (c.f. `xcb_input_send_extension_event` in [4], which has 8 iovecs for 2 lists). This also gets weird for switches, which end up taking an additional iovec when packing a list (c.f. `xcb_input_change_device_property` in [4]).

See [5] for the xcbgen implementation of this.

Also, we shouldn't pack the lists directly into the buffer, but add them to `xcb_parts`. This may be easiest to implement with a `Packer` object like the unpacker object.

[1] https://github.com/tych0/xcffib/blob/master/module/__init__.py#L364
[2] ftp://ftp.tku.edu.tw/NetBSD/NetBSD-current/src/external/mit/xorg/lib/libxcb/files/xproto.c
[3] http://cgit.freedesktop.org/xcb/proto/tree/src/xproto.xml?id=1.11
[4] ftp://ftp.tku.edu.tw/NetBSD/NetBSD-current/src/external/mit/xorg/lib/libxcb/files/xinput.c
[5] http://cgit.freedesktop.org/xcb/libxcb/tree/src/c_client.py?id=1.11#n1955

**Comment by flacjacket** [comment]
Actually, the way this packs switches is wrong, ugh, XCB, why must you be so convoluted.

**Comment by flacjacket** [comment]
Alright, so doing some RTF(xcblib)S, it looks like this mess with using multiple iovecs in xcblib is just to get the padding correct for everything, by packing up a bunch of iovecs with padding iovecs in between (the equivalent of our `-len(data) & 3` in xcblib) is the same as us putting pads in between repeated List unpacks. We just need to be sure we're packing and padding everything correctly...

**Comment by tych0** [comment]
Any word on this?

**Comment by flacjacket** [comment]
I'm not entirely sure, but I think my conclusion on that was that the
`xcb_parts` were there so the library padded everything correctly, I think
we are similar to xpyb and do the padding manually, so I don't _think_ we
need to do this.

**Comment by tych0** [comment]
Ok, I think I'll close this then :)
