### ISSUE TITLE
Travis and cairocffi failing

### ISSUE THREAD

**Issue by flacjacket** [tych0/xcffib#53]
So with the cause of the cairocffi segfault uncovered in qtile, I went and tried fixing up cairocffi. That fix is enough that I think I can unblock the test for drawing with cairo using xcffib on pixmaps, but not the test drawing directly to windows. I don't know if the fault is on the old version of cairo or on us, but I'll put this here as a reference.

Here is an xtrace from Travis [1] with it failing, tho all 6 of the tests from that build fail with a slightly different xtrace:
```
000:<:0001: 40: Request(1): CreateWindow depth=0x18 window=0x00200000 parent=0x0000012d x=0 y=0 width=10 height=10 border-width=0 class=InputOutput(0x0001) visual=0x00000021 value-list={background-pixel=0x00000000 event-mask=Exposure,StructureNotify}
000:<:0002:  8: Request(8): MapWindow window=0x00200000
000:>:0002: Event MapNotify(19) event=0x00200000 window=0x00200000 override-redirect=false(0x00)
000:>:0002: Event Expose(12) window=0x00200000 x=0 y=0 width=10 height=10 count=0x0000
000:<:0003: 20: Request(186): UNKNOWN opcode=0xba opcode2=0x04 unparsed-data=0x03,0x00,0x20,0x00,0x00,0x00,0x20,0x00,0x2a,0x00,0x00,0x00,0x00,0x00,0x00,0x00;
000:<:0004: 32: Request(186): UNKNOWN opcode=0xba opcode2=0x1a unparsed-data=0x03,0x00,0x00,0x00,0x03,0x00,0x20,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x00,0x00,0x00,0x00,0x0a,0x00,0x0a,0x00;
000:>:0003:Error 1=Request: major=186, minor=0, bad=2097152
000:<:0005: 28: Request(12): ConfigureWindow window=0x00200000 values={x=5 y=5 width=20 height=20}
000:>:0004:Error 1=Request: major=186, minor=0, bad=2097152
000:>:0005:Error 16=Length: major=8, minor=0, bad=2097152
000:>:0006:Error 16=Length: major=3, minor=0, bad=2097152
```
and an xtrace I did locally that worked:
```
000:<:0001: 40: Request(1): CreateWindow depth=0x18 window=0x00200000 parent=0x0000018e x=0 y=0 width=10 height=10 border-width=0 class=InputOutput(0x0001) visual=0x00000021 value-list={background-pixel=0x00000000 event-mask=Exposure,StructureNotify}
000:<:0002:  8: Request(8): MapWindow window=0x00200000
000:>:0002: Event MapNotify(19) event=0x00200000 window=0x00200000 override-redirect=false(0x00)
000:>:0002: Event Expose(12) window=0x00200000 x=0 y=0 width=10 height=10 count=0x0000
000:<:0003: 16: Request(98): QueryExtension name='RENDER'
000:>:0003:32: Reply to QueryExtension: present=true(0x01) major-opcode=138 first-event=0 first-error=140
000:<:0004: 24: RENDER-Request(138,4): CreatePicture pid=0x00200003 drawable=0x00200000 format=0x00000029 values={poly-mode=Imprecise(0x01)}
000:<:0005: 28: RENDER-Request(138,26): FillRectangles op=Over(0x03) dst=0x00200003 red=0xffff green=0xffff blue=0xffff alpha=0xffff rects={x=0 y=0 w=10 h=10};
000:<:0006: 28: Request(12): ConfigureWindow window=0x00200000 values={x=5 y=5 width=20 height=20}
000:>:0006: Event ConfigureNotify(22) event=0x00200000 window=0x00200000 above-sibling=None(0x00000000) x=5 y=5 width=20 height=20 border-width=0 override-redirect=false(0x00)
000:>:0006: Event Expose(12) window=0x00200000 x=0 y=0 width=20 height=20 count=0x0000
000:<:0007: 28: RENDER-Request(138,26): FillRectangles op=Over(0x03) dst=0x00200003 red=0xffff green=0xffff blue=0xffff alpha=0xffff rects={x=0 y=0 w=20 h=20};
000:<:0008:  8: RENDER-Request(138,7): FreePicture picture=0x00200003
```

It looks like cairo doesn't query the RENDER extension, I don't know if this could be fixed by creating the surface with `cairo_xcb_surface_create_with_xrender_format` rather than `cairo_xcb_surface_create`. It may be that cairo really is in the wrong here, I haven't yet tried to grok `000:<:0003: 20: Request(186): UNKNOWN opcode=0xba opcode2=0x04 unparsed-data=0x03,0x00,0x20,0x00,0x00,0x00,0x20,0x00,0x2a,0x00,0x00,0x00,0x00,0x00,0x00,0x00;`.

This issue doesn't _really_ matter, since we can just say use cairo >= 1.12, and it is probably fine.

[1] https://travis-ci.org/flacjacket/cairocffi/jobs/71201946

**Comment by tych0** [comment]
Didn't we see something like this before where cairo was doing something weird? I don't remember how that was ever resolved (perhaps it wasn't)?

**Comment by flacjacket** [comment]
We "resolved" it by saying it was a problem with cairo. There were still _some_ problems, tho they were with making sure things were free'd properly. Looking at this again this morning, this is probably the actual problem with the old cairo version, rather than a problem with us.

**Comment by tych0** [comment]
Ok, I'm going to close this then :)
