### ISSUE TITLE
Doesn't seem to make any Error types for extensions

### ISSUE THREAD

**Issue by kdienes** [tych0/xcffib#56]
It doesn't look like xcffibgen is recognizing any error values when parsing extensions:

$ grep error /usr/share/xcb/render.xml 
  <error name="PictFormat" number="0" />
  <error name="Picture" number="1" />
  <error name="PictOp" number="2" />
  <error name="GlyphSet" number="3" />
  <error name="Glyph" number="4" />

$ grep error xcffib/render.py 
_errors = {}
xcffib._add_ext(key, renderExtension, _events, _errors)

I'm sorry not to be tracking this down more thoroughly ... it's possible that I'm misunderstanding something in my hurry; if so, I apologize.

**Comment by tych0** [comment]
On Thu, Oct 22, 2015 at 06:36:43PM -0700, Klee Dienes wrote:
> It doesn't look like xcffibgen is recognizing any error values when parsing extensions:
> 
> $ grep error /usr/share/xcb/render.xml 
>   <error name="PictFormat" number="0" />
>   <error name="Picture" number="1" />
>   <error name="PictOp" number="2" />
>   <error name="GlyphSet" number="3" />
>   <error name="Glyph" number="4" />
> 
> $ grep error xcffib/render.py 
> _errors = {}
> xcffib._add_ext(key, renderExtension, _events, _errors)
> 
> I'm sorry not to be tracking this down more thoroughly ... it's possible that I'm misunderstanding something in my hurry; if so, I apologize.

I think this is actually fixed by
https://github.com/aslatter/xcb-types/commit/3bc0fddca831d42f9ff8b2cda671dc72f1224d2f

(although it looks like my upload of v0.3.6 is broken on pypi. Let me
know and I can upload a 0.3.7 that is fixed if that would be useful
for you.)

Unfortunately there is no released version with that commit, so what's
in debian is broken. @aslatter, do you mind tagging a 0.7.1 so I can
see about a debian upload?

**Comment by kdienes** [comment]
I think the Debian package is built from 1a48b24, which is your tag here of v0.3.6.

I don't know that it matters to Debian if the v0.3.6 on PyPi is broken.  If you want to upload a 0.3.7 to normalize the versions at both places, I'd certainly be glad to do the Debian upload.  Maybe it makes sense to do that after xcb-types 0.7.1 goes live, and we can use the upload of 0.3.7 to trigger a rebuild? (And maybe also put a build-depends on xcb-types (>= 0.7.1)?)

**Comment by aslatter** [comment]
@tych0 I've tagged and uploaded version 0.7.1 - sorry for the delay on that.

**Comment by kdienes** [comment]
@tych0 I'll stand by for the 0.7.1 upload and for your guidance about 0.3.7.  Let me know if there's anything you need/want from me.

**Comment by tych0** [comment]
On Fri, Oct 23, 2015 at 05:43:24AM -0700, Klee Dienes wrote:
> @tych0 I'll stand by for the 0.7.1 upload and for your guidance about 0.3.7.  Let me know if there's anything you need/want from me.

Ok. I'll probably wait to tag until Joachim uploads xcb-types, I'll
ping him now about it. Thanks @aslatter!

**Comment by tych0** [comment]
Closing this as it is resolved.
