### ISSUE TITLE
Bad struct for FillRectangles

### ISSUE THREAD

**Issue by kdienes** [tych0/xcffib#57]
In the RENDER extension, when I build with the new xcb-types-dev, I get:

    def FillRectangles(self, op, dst, color, rects, is_checked=False):
        buf = six.BytesIO()
        buf.write(struct.pack("=xB2x3xI", op, dst))

I think this should be:

        buf.write(pack('=xx2xB3xI', op, dst))

or something similar.  Will look more when I am able.

**Comment by tych0** [comment]
On Sun, Oct 25, 2015 at 01:45:24PM -0700, Klee Dienes wrote:
> In the RENDER extension, when I build with the new xcb-types-dev, I get:
> 
>     def FillRectangles(self, op, dst, color, rects, is_checked=False):
>         buf = six.BytesIO()
>         buf.write(struct.pack("=xB2x3xI", op, dst))
> 
> I think this should be:
> 
>         buf.write(pack('=xx2xB3xI', op, dst))
> 
> or something similar.  Will look more when I am able.

Hrm. Looks like this might be the same problem as #28. I wonder where
this comes from. In any case, it looks like xinerama, xfixes, xv, and
probably xselinux and a few others (although xpyb doesn't generate
these extensions) all have this same bug.

I'll see about looking for a way to figure this distinction out via
the xml, but for now I think 36c2c87e8e0996fb379b09358e67719d053232b4
should fix this?

Thanks,

Tycho

**Comment by kdienes** [comment]
I built with 36c2c87 and it fixed all the errors I've been able to find so far.  I'll be exercising it heavily over the next few days or so.

**Comment by tych0** [comment]
On Sun, Oct 25, 2015 at 07:20:03PM -0700, Klee Dienes wrote:
> I built with 36c2c87 and it fixed all the errors I've been able to find so far.  I'll be exercising it heavily over the next few days or so.

Ok, cool. I'll leave this issue open to remind me to look somewhere
for a way to distinguish how structs are packed in XML.

Do you mind posting back (or just e-mailing me off-list) when you're
happy with your stress test? I'll wait for that and then tag 0.3.7,
and then we can do an upload.

**Comment by tych0** [comment]
Ok, I've just changed the API for FillRectangles slightly (to match exactly what XCB exports). I *think* it should be ok still, but any testing would be appreciated. I'm going to close this for now, and hopefully release in the next few days. I'll ping you about an upload. Thanks!
