### ISSUE TITLE
Please included tests in pypi release

### ISSUE THREAD

**Issue by jlec** [tych0/xcffib#59]
Downstream devs love to test during packaging. Please include the tests in the pypi package to assist us.

**Comment by tych0** [comment]
On Fri, Dec 11, 2015 at 06:57:03AM -0800, Justin Lecher wrote:
> Downstream devs love to test during packaging Please include the tests in the pypi package to assist us

Sure, I'd be happy to. Is there some way people do that regularly? I'm
not very good at python packaging :)

**Comment by flacjacket** [comment]
I think we can rename `tests/` to `test/` [1], but that might only pick up
the Python files and none of the Haskell generator tests. Otherwise I think
we could add `graft tests` to `MANIFEST.in`.

[1]
https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute

**Comment by tych0** [comment]
On Fri, Dec 11, 2015 at 02:32:51PM -0800, Sean Vig wrote:
> I think we can rename `tests/` to `test/` [1], but that might only pick up
> the Python files and none of the Haskell generator tests. Otherwise I think
> we could add `graft tests` to `MANIFEST.in`.
> 
> [1]
> https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute

Cool, thanks! I'll play around with that this evening.

I don't think it's so important to pick up the haskell tests, as
what's on pypi is the output of the haskell program, so if something
was fucked up, it'll be fucked up in the pypi upload too.

**Comment by tych0** [comment]
Yep, just checked and it looks like s/tests/test works, thanks. I've pushed this commit, but I'm happy to tag a 0.4.1 if that would be useful.
