### ISSUE TITLE
add xkb

### ISSUE THREAD

**Issue by beroal** [tych0/xcffib#60]
> TODO
> xprint and xkb support. These will require some non-trivial work in xcb-types, since it won't parse them correctly.

**Comment by beroal** [comment]
[for Bountysource](https://www.bountysource.com/issues/29516116-add-xkb)

**Comment by tych0** [comment]
Well, I just implemented this in 7e2650fd21b157402cd26bff129a81a0b5ddc60c, but bountysource is NXDOMAIN, so it seems I was 9 years too late :)

**Comment by beroal** [comment]
😕
