### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by fmierlo** [tych0/xcffib#61]
Hi, I'm developing an application that will run only on Linux, but I'm using OS X for testing.

``pip install xcffib`` run without problem, I'm using OS X 10.7.5 and XQuartz 2.7.8 (xorg-server 1.16.4).

Changing the following line in the file ``xcffib/__init__.py`` was enough to load the module when running from the directory ``/opt/X11/lib``:

    #lib = ffi.dlopen ('libxcb.so.1')
    lib = ffi.dlopen ('libxcb.dylib')

Thank you for this nice work.

**Comment by tych0** [comment]
On Thu, Jan 07, 2016 at 09:26:39PM -0800, Fabio Mierlo wrote:
> 
> Hi, I'm developing an application that will run only on Linux, but I'm using OS X for testing
> 
> ``pip install xcffib`` run without problem, I'm using OS X 1075 and XQuartz 278 (xorg-server 1164)
> 
> Changing the following line in the file ``xcffib/__init__py`` was enough to load the module when running from the directory ``/opt/X11/lib``:
> 
>     #lib = ffidlopen ('libxcbso1')
>     lib = ffidlopen ('libxcbdylib')
> 
> Thank you for this nice work

Wow, I'm sort of amazed this actually works :)

Thanks, I'll see if I can figure out a way to detect and open the
right .so.

**Comment by fmierlo** [comment]
This happens when people write good software ;-)

At the moment I can not help but I believe the ``PyInstaller`` can be a good reference. I just saw that it uses ``.so`` extensions, but it creates a file called ``libgmp.10.dylib`` too.

**Comment by tych0** [comment]
Does the above work? If so, I'm happy to merge it.

**Comment by fmierlo** [comment]
It works, I just need to export the xorg library path: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/X11/lib`

Thank you.
