### ISSUE TITLE
struct.error: required argument is not an integer.

### ISSUE THREAD

**Issue by Toqozz** [tych0/xcffib#62]
While walking through the xcb python binding (http://xcb.freedesktop.org/XcbPythonBinding/), I had a few issues (unrelated to converting the example to python3).

The first was an error with the actual code it seems: `xcffib has no attribute 'XA_WM_NAME'`.  The fix is [here](http://lists.freedesktop.org/archives/xcb/2014-November/010095.html).

After this, I had further issues with the following traceback from python:
```
Traceback (most recent call last):
  File "xcb.py", line 87, in <module>
    run()
  File "xcb.py", line 63, in run
    paint()
  File "xcb.py", line 43, in paint
    conn.render.FillRectangles(xcffib.render.PictOp.Src, pid, color, 1, rectangle)
  File "/usr/lib/python3.5/site-packages/xcffib/render.py", line 687, in FillRectangles
    buf.write(color.pack() if hasattr(color, "pack") else COLOR.synthetic(*color).pack())
  File "/usr/lib/python3.5/site-packages/xcffib/render.py", line 318, in pack
    buf.write(struct.pack("=HHHH", self.red, self.green, self.blue, self.alpha))
struct.error: required argument is not an integer
```

I got the example from xcb to work by changing 
```
buf.write(struct.pack("=HHHH", self.red, self.green, self.blue, self.alpha)) (line 318)
``` 
to
```
buf.write(struct.pack("=HHHH", int(self.red), int(self.green), int(self.blue), int(self.alpha)))
``` 
and also 
```
buf.write("") (line 688)
``` 
to
```
buf.write("".encode())
``` 
in xcffib/render.py.

Now the example works as expected.

**Comment by flacjacket** [comment]
The first problem, it looks like your passing in floats where you should be passing in ints. If in the scripts you replace:
```
color = (x * 65535 / 7, y * 65535 / 5, (x * y) * 65535 / 35, 65535)
```
with
```
color = (x * 65535 // 7, y * 65535 // 5, (x * y) * 65535 // 35, 65535)
```
I think it should work.

As for the second one, we need to figure out why that line is coming in from the generator, I don't think we need the `buf.write("")` lines, of which there are many (it doesn't do anything anyways).
