### ISSUE TITLE
Can no longer create Lists from python

### ISSUE THREAD

**Issue by cknave** [tych0/xcffib#65]
I used to be able to create an XInput event mask like this:

    event_mask = xcffib.xinput.EventMask.synthetic(
        deviceid=xcffib.xinput.Device.AllMaster,
        mask_len=1,
        mask=xcffib.List.synthetic(list=[xcffib.xinput.XIEventMask.RawMotion]))

But it looks like the `synthetic` initializer for `List` went away in 06ee3a5. Is there a better way to create a `List` from python in the latest version beyond just doing what the old `synthetic` method did?

**Comment by tych0** [comment]
Good question. I think we should probably keep synthetic on List (it wasn't my intent to drop it). I'll look into re-adding it.

**Comment by tych0** [comment]
Ok, I looked at this a bit and I'm not sure that there's really a great API to be had besides what was offered by `synthetic`. I re-added it, but now you don't have to have the `list=` bit in the kwarg if you don't want. Apologies for the breakage!

**Comment by tych0** [comment]
Let me know if it would be helpful to have a release of this. I haven't done one in a while and there's some useful stuff in the queue.

**Comment by cknave** [comment]
That would be useful, thanks!

**Comment by tych0** [comment]
On Wed, Feb 10, 2016 at 06:02:30PM -0800, cknave wrote:
> That would be useful, thanks!

Cool, I just tagged and uploaded 0.4.1. I'll see about getting it into
debian sometime this week, pending the uploader's schedule :)
