### ISSUE TITLE
add `xcb_discard_reply`

### ISSUE THREAD

**Issue by orbisvicis** [tych0/xcffib#72]
What work is necessary? I assume add `discard_reply(self, sequence)` to *module/\_\_init\_\_.py::Connection* that calls `lib.xcb_discard_reply(self._conn, sequence)`, with `@ensure_connected` decorator. It is a void function so no need to call `ffi.gc`, and apparently doesn't throw any errors even on incorrect sequences, and doesn't return any response.

**Comment by orbisvicis** [comment]
and make sure `xcb_discard_reply` gets auto-generated into `_ffi.py`.

**Comment by tych0** [comment]
Closing this as I merged these patches yesterday.
