### ISSUE TITLE
Error building with xcb-proto 1.12

### ISSUE THREAD

**Issue by flacjacket** [tych0/xcffib#76]
Here is what I get trying to build against xcb-proto 1.12:

```
cabal --config-file=/dev/null build
Building xcffib-0.4.2...
Preprocessing library xcffib-0.4.2...
[1 of 2] Compiling Data.XCB.Python.PyHelpers ( generator/Data/XCB/Python/PyHelpers.hs, dist/build/Data/XCB/Python/PyHelpers.o )
[2 of 2] Compiling Data.XCB.Python.Parse ( generator/Data/XCB/Python/Parse.hs, dist/build/Data/XCB/Python/Parse.o )
In-place registering xcffib-0.4.2...
Preprocessing executable 'xcffibgen' for xcffib-0.4.2...
[1 of 3] Compiling Data.XCB.Python.PyHelpers ( generator/Data/XCB/Python/PyHelpers.hs, dist/build/xcffibgen/xcffibgen-tmp/Data/XCB/Python/PyHelpers.o ) [Data.List.Split changed]
[2 of 3] Compiling Data.XCB.Python.Parse ( generator/Data/XCB/Python/Parse.hs, dist/build/xcffibgen/xcffibgen-tmp/Data/XCB/Python/Parse.o )
[3 of 3] Compiling Main             ( generator/xcffibgen.hs, dist/build/xcffibgen/xcffibgen-tmp/Main.o ) [Options.Applicative changed]
Linking dist/build/xcffibgen/xcffibgen ...
Preprocessing test suite 'PyHelpersTests' for xcffib-0.4.2...
[1 of 1] Compiling Main             ( test/PyHelpersTests.hs, dist/build/PyHelpersTests/PyHelpersTests-tmp/Main.o )
Linking dist/build/PyHelpersTests/PyHelpersTests ...
Preprocessing test suite 'GeneratorTests.hs' for xcffib-0.4.2...
[1 of 1] Compiling Main             ( test/GeneratorTests.hs, dist/build/GeneratorTests.hs/GeneratorTests.hs-tmp/Main.o )
Linking dist/build/GeneratorTests.hs/GeneratorTests.hs ...
./dist/build/xcffibgen/xcffibgen --input /usr/share/xcb --output ./xcffib
xcffibgen: Invalid bitCase: QName {qName = "required_start_align", qURI = Nothing, qPrefix = Nothing}
make: *** [Makefile:12: xcffib] Error 1
```

This looks like it might be an xcb-types issue, but I figured I'd ping it here.

**Comment by tych0** [comment]
Thanks for the report, looks like they added a new element in the 1.12 release. I'll see about getting it into XCB types. Based on the semantics of the element, reworking xcffib is going to be a bit trickier :(

**Comment by tych0** [comment]
Here's a draft that doesn't compile, but you get the idea:

https://github.com/tych0/xcb-types/commit/3ac6e3d1365ae57c0fe4e6495974f58ce1176348

the changes are mostly mechanical.

**Comment by tych0** [comment]
I finally got around to fixing all of these, see https://github.com/aslatter/xcb-types/pull/6 for discussion. I'll push the xcffib patch when that's merged (it is considerably smaller since I just punted on all these new fields because I'm lazy :)

**Comment by felixonmars** [comment]
Is it possible to post the needed patch somewhere so we can add it as a quick patch for downstream distribution, since the xcb-types upstream seems to be inactive? Many thanks!

**Comment by tych0** [comment]
Yep, the xcffib patch is quite small, and is just HEAD of https://github.com/tych0/xcffib/tree/1.12-update, which I've just rebased as https://github.com/tych0/xcffib/commit/54822cbd5fb1f5696c66f6cfbd333a3603fc1121.

Perhaps I'll try a takeover of xcb-types if more distros need to migrate. Which are you working on?

Cheers!

**Comment by felixonmars** [comment]
I'm working on Arch, and we do not have xpyb packaged. All things that required xpyb have been patched to use xcffib instead :)

**Comment by tych0** [comment]
Cool, thanks for the info. I'm not sure what to do about xcb-types at the moment :(. Usually the upstream is pretty responsive. I'll see if there's some other option. Thanks for the ping, and sorry for the delay.

**Comment by tych0** [comment]
I've just tagged xcb-types 0.8.0 and xcffib 0.5.0, which should address this issue. Thanks to all involved!
