### ISSUE TITLE
Add a doc section to the readme

### ISSUE THREAD

**Issue by vincent-legoll** [tych0/xcffib#78]
Please add a doc section to the readme file that direct us to useful documentation : API doc, howtos, FAQs, samples, whatever is relevant...

Thanks

**Comment by tych0** [comment]
On Thu, Aug 11, 2016 at 06:08:58AM -0700, Vincent Legoll wrote:
> Please add a doc section to the readme file that direct us to useful documentation : API doc, howtos, FAQs, samples, whatever is relevant...

What exactly would you like to see here, that's not just a link to an
XCB tutorial? The design of the library is that it's essentially
exactly the same as XCB, so all of those tutorials should work just
fine.

**Comment by vincent-legoll** [comment]
Just about everything that is not explained in an XCB tutorial :-D

A few samples of python code showing us how to get a few basic things done, like a small script that given a window ID, (de-)iconifies the app it belongs to. Or smallish things like that.

**Comment by tych0** [comment]
On Fri, Aug 12, 2016 at 12:04:44AM -0700, Vincent Legoll wrote:
> Just about everything that is not explained in an XCB tutorial :-D

That's a lot :)

> A few samples of python code showing us how to get a few basic things done, like a small script that given a window ID, (de-)iconifies the app it belongs to. Or smallish things like that.

Is this a specific problem you're trying to solve? My goal is to not
fix XCB's documentation, but to provide a drop in replacement for it.
You can see smaller examples by looking at the tests, although they
don't necessarily do anything useful.

**Comment by tych0** [comment]
Closing this, as I'm not sure there's really much here to be done. I don't have the time or desire to write a bunch of docs for XCB, but I'm happy to accept patches :)
