### ISSUE TITLE
add __version__ to the module

### ISSUE THREAD

**Issue by olymk2** [tych0/xcffib#79]
Be nice if this could be added, so we can check on the version available in code.

just hit a bug which was due to me having an older version, knowing that i would like to add a check to make sure others have a new enough version of the library available.

https://www.python.org/dev/peps/pep-0396/

**Comment by tych0** [comment]
Note that if you install it with setuptools, it already sets the version through their mechanism:

```
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.require("xcffib")[0].version
>>> version
'0.4.2'
```

but it's not hard to add `__version__` as well, so I'll send a patch shortly.

**Comment by olymk2** [comment]
ah great thanks for adding that. 
I have been using a package deb file which i guess did not have this.
