### ISSUE TITLE
Errors building against xcb 1.13

### ISSUE THREAD

**Issue by flacjacket** [tych0/xcffib#88]
When building 0.5.1 against xcb 1.13, I get the following error:
```
./dist/build/xcffibgen/xcffibgen --input /usr/share/xcb --output ./xcffib
xproto
bigreq
composite
damage
dpms
dri2
dri3
ge
glx
present
randr
record
render
res
screensaver
shape
shm
sync
xc_misc
xevie
xf86dri
xf86vidmode
xfixes
xinerama
xinput
xcffibgen: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Base.hs:489:16 in containers-0.5.7.1:Data.Map.Base
make: *** [Makefile:16: xcffib] Error 1
```

Also, when I try to build the current master, just building the haskell bindings seems to fail for me like this:
```
Resolving dependencies...
Configuring xcffib-0.5.1...
Building xcffib-0.5.1...
Preprocessing library xcffib-0.5.1...
[2 of 2] Compiling Data.XCB.Python.Parse ( generator/Data/XCB/Python/Parse.hs, dist/build/Data/XCB/Python/Parse.o )
generator/Data/XCB/Python/Parse.hs:772:19: error:
    Not in scope: data constructor ‘XEventStruct’
make: *** [Makefile:34: dist/build/xcffibgen/xcffibgen] Error 1
```
I'm on xcb-types 0.8.0, rather than the current master, which it seems like you may have added some changes to that may address the xcb-proto changes, but it seems like travis is failing with similar error: https://travis-ci.org/flacjacket/xcffib/builds/349813402

**Comment by tych0** [comment]
Yeah, you need xcb-types from master; the travis failure is really bizarre though. It's cloning xcb-types from master, but XEventStruct seems to not be present somehow? Is this a caching thing? My travis build for master seems to have worked. Maybe add some debugging to see which version of xcb-types is installed?

In any case, seems like we need to do a release of the whole stack, since xcb-proto was released. I'll see about tagging everything tonight. Thanks for the heads up!

**Comment by tych0** [comment]
Ah, I think I figured out what it is: newer versions of cabal

**Comment by tych0** [comment]
Derp derp. Newer versions of cabal seem to install the released xcb-types over the top of the one you hand built, so if you do a `cabal install` of xcb-types by and, and then a `cabal install --only-dependencies`, you'll end up with the hackage version of xcb-types.

This is a relatively recent behavior change, and perhaps what broke. In any case, I'll release the new version of xcb-types so it mostly won't be a problem, and try and re-order things in travis so it also won't be a problem in the future.
